#!/usr/bin/env bash
set -e

DUMMY_USER_ID="$DUMMY_USER_ID"

if [ -z "$DUMMY_USER_ID" ]; then
    echo "Using 1000 as dummy user id..."
    DUMMY_USER_ID="1000"
fi

id dummy > /dev/null 2>&1 || { 
    echo "Creating dummy user..."
    useradd -u ${DUMMY_USER_ID} -s /bin/bash dummy
    mkdir -p /home/dummy/.ssh
}

exec gosu dummy /bin/bash "$@"